name: Auto Merge

on:
  pull_request_target:
    types:
      - labeled

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'automerge'
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Merge pull request
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: "squash"
