name: Production Version Update

on:
  push:
    branches:
      - beta

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.9'

      - name: Get next version
        id: version
        run: |
          # Simple versioning: use the commit SHA for now
          echo "::set-output name=version::${{ github.sha }}"

      - name: Update version file
        run: echo ${{ steps.version.outputs.version }} > VERSION

      - name: Commit and push version update
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update version to ${{ steps.version.outputs.version }}"
          branch: beta
          file_pattern: VERSION
