name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint with ruff
        run: |
          pip install ruff
          ruff check .
      - name: Security Analysis with Bandit
        run: |
          pip install bandit
          bandit -r .
      - name: Static Type Checking with mypy
        run: |
          pip install mypy
          mypy .
      - name: Run tests
        run: python -m unittest discover tests
