name: Production Version Update

on:
  push:
    branches:
      - main

jobs:
  update-version:
    uses: ./.github/workflows/reusable-version-update.yml
    with:
      branch: main
    permissions:
      contents: write
      pull-requests: write
