name: Reusable Version Update

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Get next version
        id: version
        run: echo "version=${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Update version file
        run: echo "${{ steps.version.outputs.version }}" > VERSION

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(version): update to ${{ steps.version.outputs.version }}"
          title: "chore(version): update to ${{ steps.version.outputs.version }}"
          body: "This is an automated PR to update the version to `${{ steps.version.outputs.version }}`."
          branch: "chore/version-update-${{ steps.version.outputs.version }}"
          base: "${{ inputs.branch }}"
          delete-branch: true
